name: travelbuddy_final
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Firebase
  firebase_core: ^4.2.0
  firebase_auth: ^6.1.1
  cloud_firestore: ^6.0.3
  cloud_functions: ^6.0.3

  # UI
  cupertino_icons: ^1.0.2
  flutter_launcher_icons: ^0.13.1

  # Maps & Location
  google_maps_flutter: ^2.5.0
  geolocator: ^14.0.2
  geocoding: ^4.0.0
  google_places_autocomplete_text_field: ^2.0.3
  dio: ^5.9.0
  flutter_polyline_points: ^3.1.0

  # API calls
  http: ^1.1.2

  # State Management
  provider: ^6.1.1

  # Utils
  intl: ^0.20.2
  shared_preferences: ^2.2.2
  url_launcher: ^6.3.0
  firebase_messaging: ^16.0.4
  flutter_local_notifications: ^19.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/logo.png"
  min_sdk_android: 21